### ISSUE TITLE
Writing hdf5 data

### ISSUE THREAD

**Issue by djps** [waltsims/k-wave-python#173]
I have had a problem with writing `p_source_input` data to h5 - it would silently crash when writing data. 

I think that the problem was in [write_matrix](https://github.com/waltsims/k-wave-python/blob/master/kwave/utils/io.py#L72) function and how this determined chunking.

Changing line 72 of io.py to
```py
    elif dims == 2:
        Nx, Ny = matrix.shape
        Nz = 1
```
seemed to resolve my problem. I am not sure whether this is a breaking change or not, or covered by existing tests.  Sorry for not yet providing a minimal working example.

**Comment by waltsims** [comment]
I'll try to add a test to write_matrix to investigate this. It does look like you are correct.

**Comment by waltsims** [comment]
If I remember correctly, we generated the test hashes with MATLAB. Is this correct @faridyagubbayli? If this is the case, we should somehow be able to still pass the test while changing the dimension assignment.

**Comment by waltsims** [comment]
We need to create a `write_matrix` collector test to evaluate this.

**Comment by peterhollender** [comment]
I'm thinking the problem may be not in the allocation of `Nx`, `Ny` and `Nz` themselves, but in assignment of `chunk_size` based off of them for 2D matrices. When `dims == 2`, `chunk_size = [Nx, 1 , 1]`, but because `Nx` is forced to be `1`, this results in a fixed `chunk_size` of `[1,1,1]`, regardless of the size of the `matrix`. 

For the `p_source_input` generated from `kWaveArray.get_distributed_source_signal`, that `matrix` can be decently large (number-of-off-grid-points (P) x signal-length (Q), in my case 12837 x 60), which results in a (1xQxP) matrix being written in (1x1x1) chunks, which takes a very long time (in my case >30s) to loop through and save as chunks (and maybe for a larger simulation causes the silent crashing @djps saw). I suspect that the issue is arising from the C/Fortran ordering compensation.  I was able to vastly improve performance by using `chunk_size = [1, 1, Nz]`  (1x1xP) for the `dims == 2` case, (it also works with `chunk_size = [Nx, Ny, Nz]` (1xQxP), `chunk_size = [1, Ny, 1]` (1xQx1), or just setting `chunks: None` for me, but this may not scale for large sims?). 

FWIW in the MATLAB version, `p_source_input` is written as a (PxQx1) matrix in chunks of (Px1x1). I'd think that intuitively you'd want each time-series in it's own chunk, but I'm not seeing big performance changes with different chunking (as long as I don't do 1x1x1).

**Comment by bvale1** [comment]
I've also just ran into this issue today 
```
DEBUG:kwave.utils.io:Nx: 1, Ny: 2030, Nz: 11486
DEBUG:kwave.utils.io:Chunk size: [1, 1, 1]
Killed
```
The 1x1x1 chunks are massively exceeding the available memory, causing a crash.
I think your solutions saved me a lot of @djps @peterhollender I'm now letting h5py automatically determine chunk size and it's running a lot better now.
