### ISSUE TITLE
Support for elastic simulations

### ISSUE THREAD

**Issue by gavinmacaulay** [waltsims/k-wave-python#26]
Any plans to support k-wave elastic simulations?

**Comment by waltsims** [comment]
Hi Gavin!

Not in the immediate term. Since this project started as an interface to the accelerated CPU and GPU binaries, the elastic formulation from MATLAB has not yet been ported. There is another interesting initiative in the form of [jwave](https://github.com/ucl-bug/jwave) which also has [an open issue](https://github.com/ucl-bug/jwave/issues/14) to migrate that code. PRs are of course welcome in this regard!

Best,
Walter
(closing for now)

**Comment by waltsims** [comment]
I have started [a Discussion](https://github.com/waltsims/k-wave-python/discussions/27) for the idea of porting elastic code to k-Wave-python. Hopefully this idea gains some traction!

**Comment by waltsims** [comment]
Lastly, it looks like [adseismic.jl](https://github.com/kailaix/ADSeismic.jl) has support for elastic simulations. It might be with which having a look there as well!

**Comment by gavinmacaulay** [comment]
Walter,

Thanks for your replies. I'll have a look at adseismic.jl. I am using k-wave in Matlab for elastic simulations but really want to move away from Matlab.

Gavin

**Comment by waltsims** [comment]
I know the feeling ;)On Sep 29, 2022, at 6:30 PM, Gavin Macaulay ***@***.***> wrote:﻿
Walter,
Thanks for your replies. I'll have a look at adseismic.jl. I am using k-wave in Matlab for elastic simulations but really want to move away from Matlab.
Gavin
